version: '3.8'
services:
  db:
     image: mysql:latest
     volumes:
       - /opt/test:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: testdb1
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306
  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - '8081:80'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
  web:
      depends_on:
        - db
      image: tomcat
      volumes:
        - /home/bscnd/Documents/m2/gla/forum/target:/usr/local/tomcat/webapps
      ports:
        - '8082:8080'
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: testdb1
        MYSQL_USER: testuser
        MYSQL_PASSWORD: root
